### PR TITLE
Support Windows

### PR DESCRIPTION
**Pull request by pgarciaq**
This PR adds support for Windows and adds support to run the test script on forks.

@waldirio Question: why are CSV files written to a temporary directory? In fact, why are CSV files written at all by default? JSON output is by default to stdout, shouldn't CSV output be to stdout too, and then have a '-o / --output' parameter to tell crhc-cli I want to write the output (be it JSON o CSV) to a file? That way, we could get rid of the temporary directory.

### CODE REVIEW

**Comment by waldirio** [comment]
Hello @pgarciaq 

Thanks for the PR. Let me answer your questions below

> why are CSV files written to a temporary directory?
We were planing to save under `/var/log`. However, once you can be executing this app as user, sometimes `/var/log` will not be allowed.

> In fact, why are CSV files written at all by default? JSON output is by default to stdout, shouldn't CSV output be to stdout too, and then have a '-o / --output' parameter to tell crhc-cli I want to write the output (be it JSON o CSV) to a file?
I like that. Can be as mentioned above or can be something like `crhc inventory list_all` with required flags, for example `--csv` or `--json`

>  That way, we could get rid of the temporary directory.
I believe this is causing problems because of Windows. Is that right?

I'll do some tests on windows box as well and I'll let you know. One attention point, there is a feature `crhc ts dump`, this guy will proceed with some dump, under `/tmp` and after that will compact all the files and after that, the customer should be able to push this package to Red Hat.

Let me analyze the best approach here, that will be great for both worlds. I'll keep you in touch.

Another point, there is an end-to-end test that you can see under `tests/end-to-end_crhc-cli_check.sh`. The main idea is test all the modules that crhc has. I'll do a small change on it and I'll share with you how to test. I'm not sure if you have any linux that you can execute it, btw, in a future, I'm planning to move this end-to-end test to pytest as well.

I hope this helps and thanks again.

**Comment by pgarciaq** [comment]
> Another point, there is an end-to-end test that you can see under `tests/end-to-end_crhc-cli_check.sh`. The main idea is test all the modules that crhc has. I'll do a small change on it and I'll share with you how to test. 

I've modified the script to support forks (with the new "-r" argument).

>I'm not sure if you have any linux that you can execute it, btw, in a future, I'm planning to move this end-to-end test to pytest as well.

It's testing on RHEL8 CSB and so far working fine.

**Comment by pgarciaq** [comment]
Resolves #89

**Comment by waldirio** [comment]
Hello @pgarciaq good morning

I was checking your branch on both environments and I got issues on both sides as well. Thanks for your code, I used that and also implement something new in order to fix and keep the code working on both sides.

Please, check this PR #144 , there you can see the changes below
```
    - Creating the files in the temporary folder (MS Windows  & Linux)
    - CSV created correctly in both environments
    - Token updated to work in both environments
    - Fix in vulnerability check, which as failing for the wrong # of pages to check
    - Creating a zip file instead of tarball, which means, working fine in both environments
```

About the end-to-end script, I created a new issue #145 , you can submit the changes there or I can do this from my side. No problem at all.

From now, there is just a test issue that skipped from my eyes on MS windows. However, you can try the latest version and confirm if everything will be working as expected.

For the next PR, please, feel free to push and contribute, but if possible in different PR's, that will be awesome.

About your question regarding the output, please, check this one #146

I'm going to archive this PR from now.

Thank you again
Waldirio

**Pull request closed without merging**
